In [15]:
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x.dot(y),'\n','----------------\n',np.dot(x,y)) # SAME DOT OPERATION USING MATRICES AND NUMPY

[[ 28.  64.]
 [ 67. 181.]] 
 ----------------
 [[ 28.  64.]
 [ 67. 181.]]


In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
import pandas as pd 
df = pd.read_csv('/home/kamran/Desktop/corona.csv')
# df.head()
# df.info()
df.describe()
df['total_cases'].max()
df.tail(50)
np.unique(df['total_cases'][df['total_cases']>100000])
# df['total_cases'].fillna(df['total_cases'].mean(),inplace=True)
df['total_cases'].head(30)
df[df.index==59790]

date location  new_cases  new_deaths  total_cases  total_deaths  \
59790  2020-12-05    World   640593.0     10198.0   66540034.0     1528868.0   

       weekly_cases  weekly_deaths  biweekly_cases  biweekly_deaths  
59790     4253632.0        76016.0       8333284.0         147329.0

In [63]:
# df[df['location']=='World']
# df[['location','total_cases']][df['total_cases'] == df['total_cases'].max()]
df = df[df['location']!='World']

In [69]:
df[['location','new_cases','new_deaths','total_deaths','total_cases']][df['total_cases'] == df['total_cases'].max()]
df[['location','new_cases','new_deaths','total_deaths','total_cases']][df['location'] == 'United States']

location  new_cases  new_deaths  total_deaths  total_cases
56927  United States        NaN         NaN           NaN          1.0
56928  United States        0.0         0.0           NaN          1.0
56929  United States        1.0         0.0           NaN          2.0
56930  United States        0.0         0.0           NaN          2.0
56931  United States        3.0         0.0           NaN          5.0
...              ...        ...         ...           ...          ...
57241  United States   180637.0      2597.0      270642.0   13721858.0
57242  United States   200055.0      2804.0      273446.0   13921913.0
57243  United States   217664.0      2879.0      276325.0   14139577.0
57244  United States   227885.0      2607.0      278932.0   14367462.0
57245  United States   213875.0      2254.0      281186.0   14581337.0

[319 rows x 5 columns]

In [76]:
df.head(3)
type(df['date'][0])
df = pd.read_csv('/home/kamran/Desktop/corona.csv', parse_dates=['date'],index='date') 
type(df['date'][0])
df.fillna({
    'date': df['date'].mode(),
    'location': df['location'].mode(),
    'new_cases': df['new_cases'].mean(),
})
df.fillna(method='ffill', limit=1) # OR bfill ie backward fill... ffill is forward fill
df.interpolate(method='any column')
df.dropna(how='all') # drop all row if all the values in the column is null
df.dropna(thresh=1) # atleast one column value shouldn't be null

pandas._libs.tslibs.timestamps.Timestamp

In [74]:
df = pd.read_csv('/home/kamran/Desktop/corona.csv',nrows=3, na_values=['n.a.','not available'])
#  OR
df = pd.read_csv('/home/kamran/Desktop/corona.csv',nrows=3, 
na_values={'total_deaths':['n.a.','not available',-1],
            'location':['n.a.','not available']})
df.to_csv('new.csv', columns=['location','total_cases','total_deaths'])
df.head()

date     location  new_cases  new_deaths  total_cases  total_deaths  \
0  2020-01-23  Afghanistan        0.0         0.0          NaN           NaN   
1  2020-01-24  Afghanistan        0.0         0.0          NaN           NaN   
2  2020-01-25  Afghanistan        0.0         0.0          NaN           NaN   

   weekly_cases  weekly_deaths  biweekly_cases  biweekly_deaths  
0           NaN            NaN             NaN              NaN  
1           NaN            NaN             NaN              NaN  
2           NaN            NaN             NaN              NaN

In [ ]:
def convert_cell(cell_entry):
    if cell_entry == 'n.a':
        return 'desired value you want to replacce n.a with'
    return cell_entry
df2 = pd.read_excel('/home/kamran/Desktop/new.xlsx','Sheet1',converter={
    'column1':convert_cell,
    'column2': convert_cell
})
df2.to_excel('new.xlsx',sheet_name='Stocks',startrow=1,startcol=2)